name: TG-bot pipeline

on:
  schedule:
    - cron: '*/5 * * * *'

# on:
#   push:
#     branches:
#       - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: cache/pip.cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running
        run: python bot.py
